language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t tharindunisal/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tharindunisal/react-test npm test

after_success:
  - docker build -t tharindunisal/multi-client ./client
  - docker build -t tharindunisal/multi-nginx ./nginx
  - docker build -t tharindunisal/multi-server ./server
  - docker build -t tharindunisal/multi-worker ./worker
  - echo "$docker_password" | docker login -u "$docker_id" --password-stdin
  - docker push tharindunisal/multi-client
  - docker push tharindunisal/multi-nginx
  - docker push tharindunisal/multi-server
  - docker push tharindunisal/multi-worker
